### ISSUE TITLE
Report: Broken Links and URLs in the Repo

### ISSUE THREAD

**Issue by MarkusSagen** [zenml-io/zenml-project-templates#6]
## Report of broken URLs  

The following urls and links appear broken in the repo and their locations:

### starter/README.md  
- [ ]  url: https://docs.zenml.io/starter-guide/pipelines#step  
- [ ]  url: https://docs.zenml.io/starter-guide/pipelines/parameters-and-caching  
- [ ]  url: https://docs.zenml.io/advanced-guide/pipelines/materializers  
- [ ]  url: https://docs.zenml.io/starter-guide/pipelines#pipeline  
- [ ]  url: https://docs.zenml.io/starter-guide/pipelines/fetching-pipelines  

---  
## All URLs  
- [ ] https://docs.zenml.io/advanced-guide/pipelines/materializers  
- [ ] https://docs.zenml.io/starter-guide/pipelines#pipeline  
- [ ] https://docs.zenml.io/starter-guide/pipelines#step  
- [ ] https://docs.zenml.io/starter-guide/pipelines/fetching-pipelines  
- [ ] https://docs.zenml.io/starter-guide/pipelines/parameters-and-caching

**Comment by htahir1** [comment]
@MarkusSagen With the latest template, all of these are fixed. Do try the new one - it features the new zenml features that are game changing!
